SUPABASE_URL="https://cwhdtrrgdgilsrixxstl.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aGR0cnJnZGdpbHNyaXh4c3RsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzM3OTE0OCwiZXhwIjoyMDc4OTU1MTQ4fQ.WMOfF6N7n1mB--ssoYPtH-5L_HBr7vJ9sN1uyXqdrPI"
